spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:events}?createDatabaseNotExist=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:1234}
    tomcat:
      test-while-idle: true
      validation-query: 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    events:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  redis:
    host: redis-db